# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

# Eu sei que é feio injetar classes desse jeito mas a gente tá com pressa
services:
    factory.services:
        class: StaticBundle\Service\ServiceFactory
        arguments: ['@doctrine.orm.default_entity_manager']

    # Serviços
    service.motorista:
        class: StaticBundle\Service\MotoristaService
        factory: ['@factory.services', 'getMotoristaService']

    service.viagem:
        class: StaticBundle\Service\ViagemService
        factory: ['@factory.services', 'getViagemService']

    service.localizacao:
        class: StaticBundle\Service\LocalizacaoService
        factory: ['@factory.services', 'getViagemService']

