<?php

namespace StaticBundle\Data\Repository;

/**
 * MotoristaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotoristaRepository extends \Doctrine\ORM\EntityRepository
{
}
